name: Restart FastAPI

on:
  push:
    branches: [ main ]

jobs:
  restart:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: sudo rm -r .venv 

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo ./.venv/bin/python3.11 -m pip install -r requirements.txt

      - name: Restart FastAPI service
        run: sudo systemctl restart backendfastapi.service
