name: Restart FastAPI

on:
  push:
    branches: [ main ]

jobs:
  restart:
    runs-on: self-hosted
    env:
      RUNNER_USER: ubuntu  # Replace with your actual username
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo ./.venv/bin/python3.11 -m pip install -r requirements.txt
      
      - name: Install dependencies
        run: |
          sudo systemctl stop backendfastapi.service

      - name: Restart FastAPI service
        run: sudo systemctl restart backendfastapi.service
