name: Restart FastAPI

on:
  push:
    branches: [ main ]


jobs:
  restart:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: |
          DIR=./.venv
          if [ -d "$DIR" ]; then
            sudo rm -r "$DIR"
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo python3.11 -m venv .venv
        
      - name: Install dependencies
        run: |
          sudo ./.venv/bin/python3.11 -m pip install -r requirements.txt

      - name: Restart FastAPI service
        run: sudo systemctl restart fastapiback.service
