name: Despliegue continuo FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-docker-image:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: sudo docker build -t my-fastapi-app .

      - name: Eliminar contenedores anteriores (Remove previous containers)
        run: |
          if [[ $(sudo docker ps -a | grep -c my-fastapi-app) -gt 0 ]]; then
            sudo docker stop my-fastapi-app
            sudo docker rm my-fastapi-app
          fi

      - name: Deploy Docker image (detached mode)
        run: sudo docker run -d  --restart always --name my-fastapi-app -p 10000:10000 my-fastapi-app
