name: Restart FastAPI

on:
  push:
    branches: [ main ]

jobs:
  restart:
    runs-on: self-hosted
    env:
      RUNNER_USER: ubuntu  # Replace with your actual username
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Optional: Only fetch the latest commit to save time
          submodules: true
          exclude: '**/*/.venv' 
      - name: Install dependencies
        run: |
          sudo ./.venv/bin/python3.11 -m pip install -r requirements.txt

      - name: Restart FastAPI service
        run: sudo systemctl restart backendfastapi.service
